In [65]:
import numpy as np

In [66]:
from gradient_check import check_layer_gradient, check_layer_param_gradient, check_model_gradient
from layers import FullyConnectedLayer, ReLULayer

In [79]:
lay = FullyConnectedLayer(3,4)

In [80]:
X = np.array([[1,2,3],[2,3,4]])

In [81]:
lay.forward(X)

array([[-0.00184694, -0.00061075,  0.00599501, -0.00526959],
       [-0.00308376, -0.0018587 ,  0.0081977 , -0.00783382]])

In [82]:
np.ones_like(X)

array([[1, 1, 1],
       [1, 1, 1]])

In [83]:
lay.backward(np.ones_like(X))

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) (3,4) 

In [78]:
np.sum(X, axis=0)

array([3, 5, 7])

In [1]:
params = {'a':11, 'b':12, 'c':13}

In [3]:
for param in params:
    print(type(param))

<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
result = {}
for param in params:
    result[param + str(5)] = params[param]

In [6]:
result

{'a5': 11, 'b5': 12, 'c5': 13}