In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,1,2,11]);arr

array([ 1,  2,  3,  4,  5,  6,  7,  1,  2, 11])

In [3]:
arr.T

array([ 1,  2,  3,  4,  5,  6,  7,  1,  2, 11])

In [4]:
arr == 1

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [5]:
arr[arr==1|3]

array([3])

In [6]:
True|3

3

### Пробуем написать код, для вычисления норм без циклов

In [7]:
A = np.arange(14).reshape(-1,2)
A

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [8]:
B = np.arange(16)[::-1].reshape(-1,2)
B

array([[15, 14],
       [13, 12],
       [11, 10],
       [ 9,  8],
       [ 7,  6],
       [ 5,  4],
       [ 3,  2],
       [ 1,  0]])

In [9]:
    def compute_distances_one_loop(a, b):
        '''
        Computes distance from every sample of X to every training sample
        Vectorizes some of the calculations, so only 1 loop is used

        Arguments:
        X, np array (num_test_samples, num_features) - samples to run
        
        Returns:
        dists, np array (num_test_samples, num_train_samples) - array
           with distances between each test and each train sample
        '''
        num_train = a.shape[0]
        num_test = b.shape[0]
        dists = np.zeros((num_test, num_train), np.float32)
        for i_test in range(num_test):
            # TODO: Fill the whole row of dists[i_test]
            # without additional loops
            dists[i_test]=np.sum(np.abs(b[i_test]-a),axis=1)
        return dists

In [10]:
dists1 = compute_distances_one_loop(A,B)

In [11]:
dists1.T.shape

(7, 8)

In [12]:
dists1.T

array([[28., 24., 20., 16., 12.,  8.,  4.,  2.],
       [24., 20., 16., 12.,  8.,  4.,  2.,  4.],
       [20., 16., 12.,  8.,  4.,  2.,  4.,  8.],
       [16., 12.,  8.,  4.,  2.,  4.,  8., 12.],
       [12.,  8.,  4.,  2.,  4.,  8., 12., 16.],
       [ 8.,  4.,  2.,  4.,  8., 12., 16., 20.],
       [ 4.,  2.,  4.,  8., 12., 16., 20., 24.]], dtype=float32)

In [13]:
print(A.shape)
print(B.shape)

(7, 2)
(8, 2)


In [14]:
print(A)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


In [15]:
print(B.T)

[[15 13 11  9  7  5  3  1]
 [14 12 10  8  6  4  2  0]]


In [16]:
An = np.expand_dims(A,axis=2)
print(An.shape)

(7, 2, 1)


In [17]:
Bn = np.expand_dims(B.T,axis=0)
print(Bn.shape)

(1, 2, 8)


In [18]:
dists = An-Bn
dists.shape

(7, 2, 8)

In [19]:
dists = np.abs(dists)

In [20]:
dists[0,:]

array([[15, 13, 11,  9,  7,  5,  3,  1],
       [13, 11,  9,  7,  5,  3,  1,  1]])

In [21]:
dists2 = np.sum(dists, axis = 1)
dists2.shape

(7, 8)

In [22]:
dists2

array([[28, 24, 20, 16, 12,  8,  4,  2],
       [24, 20, 16, 12,  8,  4,  2,  4],
       [20, 16, 12,  8,  4,  2,  4,  8],
       [16, 12,  8,  4,  2,  4,  8, 12],
       [12,  8,  4,  2,  4,  8, 12, 16],
       [ 8,  4,  2,  4,  8, 12, 16, 20],
       [ 4,  2,  4,  8, 12, 16, 20, 24]])

In [23]:
dists1.T

array([[28., 24., 20., 16., 12.,  8.,  4.,  2.],
       [24., 20., 16., 12.,  8.,  4.,  2.,  4.],
       [20., 16., 12.,  8.,  4.,  2.,  4.,  8.],
       [16., 12.,  8.,  4.,  2.,  4.,  8., 12.],
       [12.,  8.,  4.,  2.,  4.,  8., 12., 16.],
       [ 8.,  4.,  2.,  4.,  8., 12., 16., 20.],
       [ 4.,  2.,  4.,  8., 12., 16., 20., 24.]], dtype=float32)

In [24]:
np.abs(dists2) - np.abs(dists1.T)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### Проверим частичную сортировку + слайсы:

In [2]:
tmp = [9,1,3,4,8,7,2,5,6,0]

In [17]:
import bottleneck as bn
num = 3
ind = bn.partition(tmp,num)[:num]
ind

array([0, 1, 2])

In [18]:
bn.partition(tmp,num)

array([0, 1, 2, 3, 8, 7, 4, 5, 6, 9])

In [32]:
for num in range(len(tmp)):
    ind = bn.partition(tmp,num)
    print(ind, ind[:num],10*"  ", ind[num:6])

[0 1 3 4 8 7 2 5 6 9] []                      [0 1 3 4 8 7]
[0 1 3 4 8 7 2 5 6 9] [0]                      [1 3 4 8 7]
[0 1 2 4 8 7 3 5 6 9] [0 1]                      [2 4 8 7]
[0 1 2 3 8 7 4 5 6 9] [0 1 2]                      [3 8 7]
[0 1 2 3 4 7 5 6 8 9] [0 1 2 3]                      [4 7]
[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]                      [5]
[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5]                      []
[0 1 3 4 5 2 6 7 8 9] [0 1 3 4 5 2 6]                      []
[0 1 3 4 6 5 2 7 8 9] [0 1 3 4 6 5 2 7]                      []
[0 1 3 4 8 7 2 5 6 9] [0 1 3 4 8 7 2 5 6]                      []


In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  1,  2, 11])

In [5]:
arr[[1,2,5]]

array([2, 3, 6])